mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('poc.urls')),
]

handler404 = 'poc.views.error_404_view'

poc/urls.py
from django.urls import path

from . import views

app_name = 'poc'
urlpatterns = [
	path('', views.show_result_all, name='home'),
	path('resultUpload', views.result_upload_handler, name='resultUpload'),
	path('edit/remark', views.edit_remark, name='editremark'),
	path('results', views.show_result_all, name='results'),
	path('result/<int:testno>', views.show_result_detail, name='resultdetail'),
	path('chart/<int:flow_id>', views.chart_view, name='chart'),
	# path('server_side_endpoint', views.server_side_db_get, name='server-side-endpoint'),
	path('ajax/form', views.ajax_form, name='ajaxform'),
	path('settings', views.settings_page, name='settings'),
]

poc/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
# from openpyxl import Workbook
# from openpyxl import load_workbook
import csv
import re
import datetime

# Create your models here.

class settings(models.Model):
	delimiter = models.CharField(default=",", max_length=30)
	Aend_index = models.IntegerField(default=0)	
	Zend_index = models.IntegerField(default=0)	
	tag_index = models.IntegerField(default=0)	
	autogroup = models.BooleanField(default=True)

class testCase(models.Model):
	test_name = models.CharField(default="", max_length=200)
	test_description = models.CharField(default="", max_length=200)
	def __str__(self):
		return str(self.test_name) + "  ::  " + str(self.test_description)

class testUpload(models.Model):
	pub_date = models.DateTimeField('date published', default=timezone.now)
	csv_result = models.TextField(default='')
	def __str__(self):
		try:
			coresponding_relation = testResult.objects.filter(testupload_id=self.id)[0]
			testcase_id = coresponding_relation.testcase_id
			testTry_id = coresponding_relation.testtry_id
			test_no = str(testTry.objects.get(id=testTry_id).test_no)
			test_description = str(testCase.objects.get(id=testcase_id).test_description)
		except:
			test_no = ""
			test_description = ""
		return "testUpload no. " + str(self.id) + "  ::  test no. "+ test_no + "  ::  " + test_description

class testTry(models.Model):
	testcase = models.ForeignKey(testCase, on_delete=models.CASCADE, default="")
	test_no = models.IntegerField(default=0)
	remark = models.CharField(default="", max_length=200)
	pub_date = models.DateTimeField('date published', default=timezone.now)
	def __str__(self):
		return str(self.test_no)+"  ::  "+self.remark

	def result_process(self, testresultCSV, testno, testcase_id, testupload_id):

		bulk_instance = []
		reader = csv.reader(testresultCSV.split('\n'), delimiter=',')
		thead = []
		counter = 0
		for row in reader:
			if counter == 0:
				thead = row[0:]
				counter += 1
			else:
				if len(row) < 1 :
					continue
				try:
				############
					flow_name = row[thead.index('StreamBlock Name')].strip()
					drop_count = row[thead.index('Dropped Count (Frames)')].replace(',','')
					drop_time = row[thead.index('Dropped Frame Duration (us)')].replace(',','')
					tx = row[thead.index('Tx Count (Frames)')].replace(',','')
					rx = row[thead.index('Rx Sig Count (Frames)')].replace(',','')
					if int(tx) <= 0 :
						percent_drop = -1
					else:
						percent_drop = float(drop_count) / float(tx) * 100

				except IndexError:
					## return -1 mean error happened.
					return (-1, counter)
				counter += 1
				bulk_instance.append(
					testResult(
						flow_name=flow_name.strip(),
						tx=tx,
						rx=rx,
						drop_count=drop_count,
						drop_time=round(float(drop_time)/1000 ,2),
						percent_drop=round(percent_drop,5),
						testtry_id=self.id,
						testcase_id=testcase_id,
						testupload_id=testupload_id
					)
				)
		testResult.objects.bulk_create(bulk_instance)
		## return 0 mean everthing fine
		return 0

class testResult(models.Model):
	testcase = models.ForeignKey(testCase, on_delete=models.CASCADE, default="")
	testtry = models.ForeignKey(testTry, on_delete=models.CASCADE, default="")
	testupload = models.ForeignKey(testUpload, on_delete=models.CASCADE, default="")
	flow_name = models.CharField(default="", max_length=200)
	tx = models.BigIntegerField(default=0)
	rx = models.BigIntegerField(default=0)
	pub_date = models.DateTimeField('date published', default=timezone.now)
	drop_count = models.BigIntegerField(default=0)
	drop_time = models.FloatField(default=0.0)
	percent_drop = models.FloatField(default=0.0)

	def __str__(self):
		return str(self.testtry_id)+':'+self.flow_name+' drop: '+str(self.drop_count)

poc/views.py
from django.shortcuts import render, get_object_or_404,get_list_or_404
from django.http import HttpResponseRedirect,JsonResponse
from django.urls import reverse
from django.conf import settings
from django.db.models import Max
from django.db.models import Q
from django.utils import timezone

from django.core.files.storage import FileSystemStorage
from chartit import DataPool, Chart
# Create your views here.
import re
from .models import testCase, testResult, testTry, testUpload, settings

def error_404_view(request, exception):
	return render(request,'poc/404.html')

def result_upload_handler(request):
	#####
	## for after upload result
	#####
	trigger_warning = False
	if request.method == 'POST' and request.POST['testresult']:
		testupload = testUpload(csv_result=request.POST['testresult'])
		testupload.save()
		###
		# this block is for existing test no.
		###
		try:
			tt = testTry.objects.get(test_no=request.POST['testno'])
			## check if all data can store correctly in data
			result_process_output = tt.result_process(request.POST['testresult'], request.POST['testno'], request.POST['testcase'], testupload.id)
			if result_process_output != 0:
			## if any error happend in this process not store any data and push alert
			## render same upload page with alert
				try:
					testcase = testCase.objects.all().order_by('test_name')
					latest_testtry = testTry.objects.all().aggregate(Max('test_no'))
					test_case = testTry.objects.select_related("testcase").get(test_no=latest_testtry['test_no__max'])
				except testTry.DoesNotExist:
					latest_testtry = {'test_no__max':1}
					test_case = ''
				trigger_warning = True
				error_msg = f"Found problem in result line {result_process_output[1]} . Please check if the CSV format is vaild or not." 
				context = {'testcase': testcase, 'latest_testtry':latest_testtry, 'test_case_name':test_case, 'trigger_warning': trigger_warning, "error_msg": error_msg}
				return render(request, 'poc/upload_result.html', context)
			# return render(request, 'poc/upload_result.html')
			return HttpResponseRedirect(reverse('poc:resultdetail', args=(request.POST['testno'],)))
		###
		# this block is for new test no.
		###
		except testTry.DoesNotExist:
			result = testTry(test_no=request.POST['testno'], testcase_id=request.POST['testcase'])
			result.save()
			## check if all data can store correctly in data
			result_process_output = result.result_process(request.POST['testresult'], request.POST['testno'], request.POST['testcase'], testupload.id)
			if result_process_output != 0:
			## if any error happend in this process not store any data and push alert
			## render same upload page with alert
				## delete current testTry because of it error.
				testTry.objects.filter(test_no=request.POST['testno']).delete()
				try:
					testcase = testCase.objects.all().order_by('test_name')
					latest_testtry = testTry.objects.all().aggregate(Max('test_no'))
					test_case = testTry.objects.select_related("testcase").get(test_no=latest_testtry['test_no__max'])
				except testTry.DoesNotExist:
					latest_testtry = {'test_no__max':1}
					test_case = ''
				trigger_warning = True
				error_msg = f"Found a problem in result line {result_process_output[1]} . Please check if the CSV format from spirent is vaild or not." 
				context = {'testcase': testcase, 'latest_testtry':latest_testtry, 'test_case_name':test_case, 'trigger_warning': trigger_warning, "error_msg": error_msg}
				return render(request, 'poc/upload_result.html', context)
			return HttpResponseRedirect(reverse('poc:resultdetail', args=(request.POST['testno'],)))

	#####
	## for before upload result
	#####
	else:
		try:
			testcase = testCase.objects.all().order_by('test_name')
			latest_testtry = testTry.objects.all().aggregate(Max('test_no'))
			test_case = testTry.objects.select_related("testcase").get(test_no=latest_testtry['test_no__max'])
		except testTry.DoesNotExist:
			latest_testtry = {'test_no__max':1}
			test_case = ''
		context = {'testcase': testcase, 'latest_testtry':latest_testtry, 'test_case_name':test_case, 'trigger_warning': trigger_warning}
		return render(request, 'poc/upload_result.html', context)

def show_result_detail(request,testno):
	try:
		queried_flow = testResult.objects.select_related('testtry').filter(testtry__test_no=testno)
		testcase_name =queried_flow[0].testcase
		settings_object = settings.objects.first()
		delimiter = settings_object.delimiter
		Aend_index = settings_object.Aend_index
		Zend_index = settings_object.Zend_index
		tag_index = settings_object.tag_index
		
		trigger_warning = False
		result_dict = {}
		results = []
		for row in queried_flow:
			result_row = {}
			result_row['flow_name'] = row.flow_name
			result_row['id'] = row.id
			result_row['rx'] = row.rx
			result_row['tx'] = row.tx
			result_row['drop_count'] = row.drop_count
			result_row['drop_time'] = row.drop_time
			if row.tx - row.rx != 0 :
				result_row['dead'] = 'yes' if (((row.tx - row.rx) - row.drop_count) /(row.tx - row.rx)) *100  > 30 else 'no'
			else:
				result_row['dead'] = 'no'
			result_row['percent_drop'] = row.percent_drop
			result_row['test_no'] = row.testtry.test_no
			flow_name_sp_list = row.flow_name.split(delimiter)
			try:
				result_row['custom_col'] = {
					'source': flow_name_sp_list[Aend_index],
					'destination': flow_name_sp_list[Zend_index],
					'tag': flow_name_sp_list[tag_index]
				}
				result_row['is_custom_col_vaild'] = True
				if row.flow_name not in result_dict:
					update = {
						row.flow_name: {
							"tx": row.tx,
							"rx": row.rx,
							"id": row.id,
							"drop_count": row.drop_count,
							"drop_time": row.drop_time,
							"percent_drop": row.percent_drop,
							"test_no": row.testtry.test_no,
							"custom_col": {
								'source': flow_name_sp_list[Aend_index],
								'destination': flow_name_sp_list[Zend_index],
								'tag': flow_name_sp_list[tag_index]
							},
							"is_custom_col_vaild": True
						}
					}
					result_dict.update(update)
				elif result_dict[row.flow_name]["drop_time"] < row.drop_time:
					update = {
						row.flow_name: {
							"tx": row.tx,
							"rx": row.rx,
							"id": row.id,
							"drop_count": row.drop_count,
							"drop_time": row.drop_time,
							"percent_drop": row.percent_drop,
							"test_no": row.testtry.test_no,
							"custom_col": {
								'source': flow_name_sp_list[Aend_index],
								'destination': flow_name_sp_list[Zend_index],
								'tag': flow_name_sp_list[tag_index]
							},
							"is_custom_col_vaild": True
						}
					}
					result_dict.update(update)
			except IndexError:
				update = {
					row.flow_name: {
						"tx": row.tx,
						"rx": row.rx,
						"id": row.id,
						"drop_count": row.drop_count,
						"drop_time": row.drop_time,
						"percent_drop": row.percent_drop,
						"test_no": row.testtry.test_no,
						"is_custom_col_vaild": False
					}
				}
				result_dict.update(update)
				result_row['custom_col'] = {
					'source': '-',
					'destination': '-',
					'tag': '-'
				}
				result_row['is_custom_col_vaild'] = True
				trigger_warning = True
			results.append(result_row)

		if settings.objects.first().autogroup:
			results = []
			for flow_name, value in result_dict.items():
				if 'custom_col' in value:
					results.append(
						{
							"flow_name": flow_name,
							"tx": value['tx'],
							"rx": value['rx'],
							"id": value['id'],
							"drop_count": value['drop_count'],
							"drop_time": value['drop_time'],
							"percent_drop": value['percent_drop'],
							"test_no": value['test_no'],
							"custom_col": {
								'source': value['custom_col']['source'],
								'destination': value['custom_col']['destination'],
								'tag': value['custom_col']['tag']
							},
							"is_custom_col_vaild": True
						}
					)
				else:
					results.append(
						{
							"flow_name": flow_name,
							"tx": value['tx'],
							"rx": value['rx'],
							"id": value['id'],
							"drop_count": value['drop_count'],
							"drop_time": value['drop_time'],
							"percent_drop": value['percent_drop'],
							"test_no": value['test_no'],
							"custom_col": {
								'source': "-",
								'destination': "-",
								'tag': "-"
							},
							"is_custom_col_vaild": True
						}
					)
			context = {'results': results, 'testcase_name':testcase_name, 'testno':testno, 'trigger_warning':trigger_warning}
		else:
			context = {'results': results, 'testcase_name':testcase_name, 'testno':testno, 'trigger_warning':trigger_warning}
		return render(request, 'poc/result_detail.html', context)
	except testResult.DoesNotExist:
		return render(request, 'poc/result_detail.html')
	except IndexError:
		return render(request, 'poc/result_detail.html')

def show_result_all(request):
	queried_flow = testTry.objects.select_related('testcase')
	context = {'rows': queried_flow}
	return render(request, 'poc/results.html', context)

def edit_remark(request):
	if request.method == 'POST':
		test_no = request.POST['test_no']
		remark = request.POST['remark']
		# print (test_no, remark)
		doc = testTry.objects.filter(test_no=test_no).update(remark=remark)

		return HttpResponseRedirect(reverse('poc:results'))

def chart_view(request, flow_id):
	flow_name = get_object_or_404(testResult, id=flow_id).flow_name
	testcase_id = get_object_or_404(testResult, id=flow_id).testcase_id
	test_description = get_object_or_404(testCase, id=testcase_id).test_description

	#From Chartit.
	#Step 1: Create a DataPool with the data we want to retrieve.
	chartdata = DataPool(
		series=
		[
			{
			 'options': { 'source': testResult.objects.filter(flow_name=flow_name ,testcase_id=testcase_id).order_by('pub_date')[:40] },
			 'terms': ['pub_date','drop_time']
			 }
		]
	)
	#Step 2: Create the Chart object
	cht = Chart(
		datasource = chartdata,
		series_options =
			[{'options':{
				'type': 'line',
				'stacking': False
			  },
			  'terms':{
				'pub_date': ['drop_time']
			  }
			}],
		chart_options =
		{

poc/templates/poc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand" href="{% url 'poc:home' %}">Spirent result portal</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-main-nav" aria-expanded="false">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbar-main-nav">
		<ul class="navbar-nav">
			<li class="nav-item">
				<a class="nav-link" href="{% url 'poc:resultUpload' %}">Upload Result</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'poc:results' %}">View Result</a>
			</li>
		</ul>
		<ul class="navbar-nav ml-auto">
			<li class="nav-item">
				<a class="nav-link" href="{% url 'poc:settings' %}">Settings</a>
			</li>
		</ul>
	</div>
</nav>

poc/templates/poc/result.html
{% extends 'poc/base.html' %}

{% load static %}

{% block content %}

<div class="show-result-container d-flex h-100 p-3 mx-auto flex-column">
    {% if latest_flow %}
        <div class="row">
            <div class="col-12">
                <div class="float-right btn-group mr-2">
                    <a href="{% url 'poc:summary' test_set %}" class="btn btn-sm btn-outline-secondary">Summary</a>
                    <a href="" class="btn btn-sm btn-outline-secondary">View all test</a>
                </div>
            </div>
        </div>
        <div>
            <h3>
                {{ desc }}
            </h3>
        </div>
        <table id="table_id" class="display">
            <thead>
                <tr>
                    <th>Flow Name</th>
                    <th>Tx</th>
                    <th>Rx</th>
                    <th>Drop</th>
                    <th>Drop time</th>
                    <th>Testset</th>
                    <th>Service</th>
                    <th>BG</th>
                    <th>datetime</th>

                </tr>
            </thead>
            <tbody>
            {% for row in latest_flow %}
                <tr>
                    <td><a href="{% url 'poc:chart' row.id %}">{{ row.flow_name }}</a></td>
                    <td>{{ row.tx }}</td>
                    <td>{{ row.rx }}</td>
                    <td>{{ row.drop_count }}</td>
                    <td>{{ row.drop_time }}</td>
                    <td>{{ row.test_set }}</td>
                    <td>{{ row.service_type }}</td>
                    <td>{{ row.bg_service }}</td>
                    <td>{{ row.pub_date }}</td>

                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th>Flow Name</th>
                    <th>Tx</th>
                    <th>Rx</th>
                    <th>Drop</th>
                    <th>Drop time (ms)</th>
                    <th>Testset</th>
                    <th>Service type</th>
                    <th>BG</th>
                    <th>datetime</th>

                </tr>
            </tfoot>
        </table>
    {% else %}
        <p>
            No Data.
        </p>
    {% endif %}
</div>
{% endblock %}

poc/templates/poc/result_detail.html
{% extends 'poc/base.html' %}

{% load static %}
{% load mathfilters %}

{% block title %}Result detail{% endblock %}


{% block content %}

<div class="show-result-container d-flex h-100 p-3 mx-auto flex-column">
	{% if results %}
		<div class="row">
			<div class="col-6">
				<h3 class="inline">
					Testcase {{testcase_name.test_name}}.
				</h3>
				<h5 class="inline">
					{{ testcase_name.test_description }}
				</h5>
			</div>
			<div class="col-6">
				<div class="float-right btn-group mr-2">
					<a href="{% url 'poc:results' %}" class="btn btn-sm btn-outline-secondary">View all test</a>
				</div>
			</div>
		</div>
		{% if trigger_warning %}
		<div class="alert alert-warning alert-dismissible fade show" role="alert">
			<strong>Warning!</strong> We cannot extract field from flow name in some row. Please check your <a href="{% url 'poc:settings' %}">setting</a>.
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		{% endif %}
		<table id="table_resultdetail" class="display">
			<thead>
				<tr>
					<th>Flow Name</th>
					<th>Tx(frames)</th>
					<th>Rx(frames)</th>
					<th>Tx - Rx</th>
					<th>Drop(frames)</th>
					<th>Dead</th>
					<th>Drop time(ms)</th>
					<th>Drop %</th>
					<th>no.</th>
					<th>src</th>
					<th>dst</th>
					<th>tag</th>
				</tr>
			</thead>
			<tbody>
			{% for row in results %}
				<tr>
					<td><a href="{% url 'poc:chart' row.id %}">{{ row.flow_name }}</a></td>
					<td>{{ row.tx }}</td>
					<td>{{ row.rx }}</td>
					<td>{{ row.tx|sub:row.rx }}</td>
					<td>{{ row.drop_count }}</td>
					<td>{{ row.dead }}</td>
					<td>{{ row.drop_time }}</td>
					<td>{{ row.percent_drop }}</td>
					<td>{{ row.test_no }}</td>
					{% if row.is_custom_col_vaild %}
						<td>{{ row.custom_col.source }}</td>
						<td>{{ row.custom_col.destination }}</td>
						<td>{{ row.custom_col.tag }}</td>
					{% endif %}
				</tr>
			{% endfor %}
			</tbody>
			<tfoot>
				<tr>
					<th>Flow Name</th>
					<th>Tx(frames)</th>
					<th>Rx(frames)</th>
					<th>Tx - Rx</th>
					<th>Drop(frames)</th>
					<th>Dead</th>
					<th>Drop time(ms)</th>
					<th>Drop %</th>
					<th>no.</th>
					<th>src</th>
					<th>dst</th>
					<th>tag</th>
				</tr>
			</tfoot>
		</table>
	{% else %}
		<p>
			Not found any data.
		</p>
	{% endif %}
</div>
{% endblock %}

poc/templates/poc/results.html
{% extends 'poc/base.html' %} {% load static %} {% block title %}PoC Result{% endblock %} {% block content %}

<div class="show-result-container d-flex h-100 p-3 mx-auto flex-column">
    <div>
        <h3>
            {{ desc }}
        </h3>
    </div>
    <table id="table_alltestcases" class="display">
        <thead>
            <tr>
                <th>no.</th>
                <th>testcase</th>
                <th>Description</th>
                <th>Remark</th>
                <th>Operation</th>
                <th>upload at</th>
            </tr>
        </thead>
        <tbody>
            {% for row in rows %}
            <tr>
                <td>{{ row.test_no }}</td>
                <td>{{ row.testcase.test_name }}</td>
                <td><a href="{% url 'poc:resultdetail' row.test_no %}">{{ row.testcase.test_description }}</a></td>
                <td>{{ row.remark }}</td>
                <td class="center">
                    <a
                        href="#my_modal"
                        data-toggle="modal"
                        data-target="#edit_remark_modal"
                        data-text="{{ row.remark }}"
                        data-set="{{ row.test_no }}"
                        >Edit remark</a
                    >
                </td>
                <td>{{ row.pub_date }}</td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th>no.</th>
                <th>testcase</th>
                <th>Description</th>
                <th>Remark</th>
                <th>Operation</th>
                <th>upload at</th>
            </tr>
        </tfoot>
    </table>
    <!-- Modal -->
    <div
        class="modal fade"
        id="edit_remark_modal"
        tabindex="-1"
        role="dialog"
        aria-labelledby="exampleModalCenterTitle"
        aria-hidden="true"
    >
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Edit Remark</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form class="tagForm" method="post" action="{% url 'poc:editremark' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="remark" class="col-form-label">Remark</label>
                            <input type="text" id="remark_textbox" class="form-control" name="remark" value="" />
                            <input type="hidden" class="form-control" name="test_no" value="" />
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
</div>

poc/templates/poc/settings.html
{% extends 'poc/base.html' %} {% load static %} {% block title %}Settings{% endblock %} {% block content %}

<div class="container mt-5">
    <h2 class="mb-5">Settings</h2>
    <div class="setting-card">
        <form action="{% url 'poc:settings'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Field delimiter</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="delimiter" value="{{ context.delimiter }}">
                </div>
                <p class="description-box col-sm-6">A single character or word that use as a separator to streamname.</p>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Tag index</label>
                <div class="col-sm-4">
                    <input type="number" class="form-control" name="tag_index" value="{{ context.tag_index }}">
                </div>
                <p class="description-box col-sm-6">A number that indicate arbitary tag from stream-name(separated by delimiter).</br>An index start from 0 (tag can be use as service-name, vpn-name, etc.)</p>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">A-end index</label>
                <div class="col-sm-4">
                    <input type="number" class="form-control" name="Aend_index" value="{{ context.Aend_index }}">
                </div>
                <p class="description-box col-sm-6">A number that indicate source field in stream-name</br>An index start from 0</p>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Z-end index</label>
                <div class="col-sm-4">
                    <input type="number" class="form-control" name="Zend_index" value="{{ context.Zend_index }}">
                </div>
                <p class="description-box col-sm-6">A number that indicate destination field in stream-name</br>An index start from 0</p>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Automatic group by stream-name</label>
                <div class="col-sm-4">
                    <div id="toggles">
                        {% if context.autogroup %}
                        <input type="checkbox" name="checkbox" id="checkbox1" class="ios-toggle" checked/>
                        {% else %}
                        <input type="checkbox" name="checkbox" id="checkbox1" class="ios-toggle"/>
                        {% endif %}
                        <label for="checkbox1" class="checkbox-label" data-off="off" data-on="on"></label>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button class="btn btn-primary" type="submit">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

poc/templates/poc/upload_result.html
{% extends 'poc/base.html' %} {% block title %}Result Upload{% endblock %} {% block content %}

<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
    <main role="main" class="inner cover">
        <h1 class="cover-heading">Upload your results.</h1>
        {% if trigger_warning %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Error occured!</strong> {{ error_msg }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
        </div>
        {% endif %}
        <form action="{% url 'poc:resultUpload'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %} {% if testcase %}
            <div class="form-group selDiv">
                <label for="sel1">Select Testcase:</label>
                <select name="testcase" class="form-control" id="sel1">
					{% for row in testcase %}
						{% if test_case_name.testcase.test_description in row.test_description %}
							<option value="{{ row.id }}" selected>{{ row.test_name }}. {{row.test_description}}</option>
						{% else %}
							<option value="{{ row.id }}" >{{ row.test_name }}. {{row.test_description}}</option>
						{% endif %}
					{% endfor %}
				</select>
            </div>
            {% else %}
            <div class="form-group">
                <label for="sel1">Select Testcase:</label>
                <select name="testcase" class="form-control" id="sel1">
						<option>NO TESTCASE AVAILABLE PLEASE ADD IT FIRST.</option>
					</select>
            </div>
            {% endif %}
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Test no.</label>
                <div class="col-sm-10">
                    <input type="number" class="form-control" name="testno" value="{{ latest_testtry.test_no__max }}">
                </div>
            </div>
            <div class="form-group">
                <label>Paste result here:</label>
                <textarea name="testresult" class="form-control" rows="5"></textarea>
                <div class="col-sm-10 py-3 px-0">
                    <button class="btn btn-primary" type="submit">Upload</button>
                </div>
            </div>
        </form>
    </main>
</div>

{% endblock %}